baseURL = "https://delphi.cmu.edu/blog"
languageCode = "en-us"
title = "Words from the Oracle"
theme = "cmu"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeURLs = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "https://delphi.cmu.edu/blog/"
[[menu.main]]
    name = "Delphi"
    url = "https://delphi.cmu.edu"
[[menu.main]]
    name = "COVIDcast"
    url = "https://covidcast.cmu.edu"
[[menu.main]]
    name = "API"
    url = "https://cmu-delphi.github.io/delphi-epidata/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/cmu-delphi"

[params]
    description = "The blog of the Delphi group at Carnegie Mellon University."
    highlight = true
    math = true
    [params.logo]
    url = "delphi_logo.png"
    width = 50
    height = 50
    alt = "Logo"

