on:
  push

name: ci

# based on https://github.com/r-lib/actions/blob/master/examples/blogdown.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
      - name: Setup R
        run: |
          conda install r pandoc r-cairo
      - name: Run Prepare Script
        run: |
          Rscript ./R/prepare.R
      - name: Build site
        run: |
          Rscript -e 'blogdown::build_site()'

      - name: Deploy Main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public

